apiVersion: v1
kind: Service
metadata:
  name: ollama-worker01
  namespace: silicon-valet
spec:
  selector:
    app: ollama
    node-role: worker01
  ports:
    - port: 11434
      targetPort: 11434
      name: ollama
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-worker02
  namespace: silicon-valet
spec:
  selector:
    app: ollama
    node-role: worker02
  ports:
    - port: 11434
      targetPort: 11434
      name: ollama
  type: ClusterIP
