apiVersion: v1
kind: Service
metadata:
  name: valet
  namespace: silicon-valet
spec:
  selector:
    app: valet-core
  ports:
    - port: 7443
      targetPort: 7443
      nodePort: 30743
      name: websocket
  type: NodePort
